### ISSUE TITLE
Command `make build-nogui` fails on Alpine Linux 3.17.1

### ISSUE THREAD

**Issue by gjskha** [ProtonMail/proton-bridge#332] opened 2023-01-17 08:02 UTC
## Expected Behavior
It should compile

## Current Behavior

```
$ make build-nogui
go build -tags='' -ldflags '-X github.com/ProtonMail/proton-bridge/v3/internal/constants.Version=3.0.6+git -X github.com/ProtonMail/proton-bridge/v3/internal/constants.Revision=f070314524 -X github.com/ProtonMail/proton-bridge/v3/internal/constants.BuildTime=2023-01-16T23:57:36-0800 -X "github.com/ProtonMail/proton-bridge/v3/internal/constants.FullAppName=Proton Mail Bridge"' -o "proton-bridge" "./cmd/Desktop-Bridge/"
# github.com/ProtonMail/proton-bridge/v3/cmd/Desktop-Bridge
/usr/lib/go/pkg/tool/linux_amd64/link: running g++ failed: exit status 1
/usr/lib/gcc/x86_64-alpine-linux-musl/12.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: /root/go/pkg/mod/github.com/!proton!mail/gluon@v0.14.2-0.20221206104410-725ddb9db68a/internal/parser/lib/Linux/x86_64/libprotobuf.a(message_lite.cc.o): in function `google::protobuf::MessageLite::SerializePartialToZeroCopyStream(google::protobuf::io::ZeroCopyOutputStream*) const':
message_lite.cc:(.text+0x11da): undefined reference to `__memcpy_chk'
/usr/lib/gcc/x86_64-alpine-linux-musl/12.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: /root/go/pkg/mod/github.com/!proton!mail/gluon@v0.14.2-0.20221206104410-725ddb9db68a/internal/parser/lib/Linux/x86_64/libprotobuf.a(message_lite.cc.o): in function `bool google::protobuf::internal::MergeFromImpl<false>(google::protobuf::stringpiece_internal::StringPiece, google::protobuf::MessageLite*, google::protobuf::MessageLite::ParseFlags)':
message_lite.cc:(.text._ZN6google8protobuf8internal13MergeFromImplILb0EEEbNS0_20stringpiece_internal11StringPieceEPNS0_11MessageLiteENS5_10ParseFlagsE[_ZN6google8protobuf8internal13MergeFromImplILb0EEEbNS0_20stringpiece_internal11StringPieceEPNS0_11MessageLiteENS5_10ParseFlagsE]+0x121): undefined reference to `__memcpy_chk'
/usr/lib/gcc/x86_64-alpine-linux-musl/12.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: /root/go/pkg/mod/github.com/!proton!mail/gluon@v0.14.2-0.20221206104410-725ddb9db68a/internal/parser/lib/Linux/x86_64/libprotobuf.a(message_lite.cc.o): in function `bool google::protobuf::internal::MergeFromImpl<true>(google::protobuf::stringpiece_internal::StringPiece, google::protobuf::MessageLite*, google::protobuf::MessageLite::ParseFlags)':
message_lite.cc:(.text._ZN6google8protobuf8internal13MergeFromImplILb1EEEbNS0_20stringpiece_internal11StringPieceEPNS0_11MessageLiteENS5_10ParseFlagsE[_ZN6google8protobuf8internal13MergeFromImplILb1EEEbNS0_20stringpiece_internal11StringPieceEPNS0_11MessageLiteENS5_10ParseFlagsE]+0x131): undefined reference to `__memcpy_chk'
/usr/lib/gcc/x86_64-alpine-linux-musl/12.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: /root/go/pkg/mod/github.com/!proton!mail/gluon@v0.14.2-0.20221206104410-725ddb9db68a/internal/parser/lib/Linux/x86_64/libprotobuf.a(common.cc.o): in function `google::protobuf::internal::DefaultLogHandler(google::protobuf::LogLevel, char const*, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
common.cc:(.text+0x5f): undefined reference to `__fprintf_chk'
/usr/lib/gcc/x86_64-alpine-linux-musl/12.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: /root/go/pkg/mod/github.com/!proton!mail/gluon@v0.14.2-0.20221206104410-725ddb9db68a/internal/parser/lib/Linux/x86_64/libprotobuf.a(common.cc.o): in function `google::protobuf::internal::VersionString[abi:cxx11](int)':
common.cc:(.text+0x176): undefined reference to `__snprintf_chk'
/usr/lib/gcc/x86_64-alpine-linux-musl/12.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: /root/go/pkg/mod/github.com/!proton!mail/gluon@v0.14.2-0.20221206104410-725ddb9db68a/internal/parser/lib/Linux/x86_64/libprotobuf.a(strutil.cc.o): in function `google::protobuf::CEscapeInternal(char const*, int, char*, int, bool, bool)':
strutil.cc:(.text+0xb90): undefined reference to `__sprintf_chk'
/usr/lib/gcc/x86_64-alpine-linux-musl/12.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: /root/go/pkg/mod/github.com/!proton!mail/gluon@v0.14.2-0.20221206104410-725ddb9db68a/internal/parser/lib/Linux/x86_64/libprotobuf.a(strutil.cc.o): in function `google::protobuf::FloatToBuffer(float, char*)':
strutil.cc:(.text+0x388d): undefined reference to `__snprintf_chk'
/usr/lib/gcc/x86_64-alpine-linux-musl/12.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: strutil.cc:(.text+0x3907): undefined reference to `__snprintf_chk'
/usr/lib/gcc/x86_64-alpine-linux-musl/12.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: /root/go/pkg/mod/github.com/!proton!mail/gluon@v0.14.2-0.20221206104410-725ddb9db68a/internal/parser/lib/Linux/x86_64/libprotobuf.a(strutil.cc.o): in function `google::protobuf::internal::NoLocaleStrtod(char const*, char**)':
strutil.cc:(.text+0x5bbe): undefined reference to `__snprintf_chk'
/usr/lib/gcc/x86_64-alpine-linux-musl/12.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: /root/go/pkg/mod/github.com/!proton!mail/gluon@v0.14.2-0.20221206104410-725ddb9db68a/internal/parser/lib/Linux/x86_64/libprotobuf.a(strutil.cc.o): in function `google::protobuf::DoubleToBuffer(double, char*)':
strutil.cc:(.text+0x5ef8): undefined reference to `__snprintf_chk'
/usr/lib/gcc/x86_64-alpine-linux-musl/12.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: strutil.cc:(.text+0x5f7b): undefined reference to `__snprintf_chk'
/usr/lib/gcc/x86_64-alpine-linux-musl/12.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: /root/go/pkg/mod/github.com/!proton!mail/gluon@v0.14.2-0.20221206104410-725ddb9db68a/internal/parser/lib/Linux/x86_64/libprotobuf.a(extension_set_heavy.cc.o): in function `char const* google::protobuf::internal::ExtensionSet::ParseMessageSetItemTmpl<google::protobuf::Message, google::protobuf::UnknownFieldSet>(char const*, google::protobuf::Message const*, google::protobuf::internal::InternalMetadata*, google::protobuf::internal::ParseContext*)':
extension_set_heavy.cc:(.text._ZN6google8protobuf8internal12ExtensionSet23ParseMessageSetItemTmplINS0_7MessageENS0_15UnknownFieldSetEEEPKcS7_PKT_PNS1_16InternalMetadataEPNS1_12ParseContextE[_ZN6google8protobuf8internal12ExtensionSet23ParseMessageSetItemTmplINS0_7MessageENS0_15UnknownFieldSetEEEPKcS7_PKT_PNS1_16InternalMetadataEPNS1_12ParseContextE]+0x815): undefined reference to `__memcpy_chk'
/usr/lib/gcc/x86_64-alpine-linux-musl/12.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: /root/go/pkg/mod/github.com/!proton!mail/gluon@v0.14.2-0.20221206104410-725ddb9db68a/internal/parser/lib/Linux/x86_64/libprotobuf.a(text_format.cc.o): in function `google::protobuf::Message::PrintDebugString() const':
text_format.cc:(.text+0x8e67): undefined reference to `__printf_chk'
/usr/lib/gcc/x86_64-alpine-linux-musl/12.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: /root/go/pkg/mod/github.com/!proton!mail/gluon@v0.14.2-0.20221206104410-725ddb9db68a/internal/parser/lib/Linux/x86_64/libprotobuf.a(wire_format.cc.o): in function `google::protobuf::internal::WireFormat::MessageSetParser::_InternalParse(char const*, google::protobuf::internal::ParseContext*)':
wire_format.cc:(.text._ZN6google8protobuf8internal10WireFormat16MessageSetParser14_InternalParseEPKcPNS1_12ParseContextE[_ZN6google8protobuf8internal10WireFormat16MessageSetParser14_InternalParseEPKcPNS1_12ParseContextE]+0x66b): undefined reference to `__memcpy_chk'
/usr/lib/gcc/x86_64-alpine-linux-musl/12.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: /root/go/pkg/mod/github.com/!proton!mail/gluon@v0.14.2-0.20221206104410-725ddb9db68a/internal/parser/lib/Linux/x86_64/libprotobuf.a(extension_set.cc.o): in function `char const* google::protobuf::internal::ExtensionSet::ParseMessageSetItemTmpl<google::protobuf::MessageLite, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(char const*, google::protobuf::MessageLite const*, google::protobuf::internal::InternalMetadata*, google::protobuf::internal::ParseContext*)':
extension_set.cc:(.text._ZN6google8protobuf8internal12ExtensionSet23ParseMessageSetItemTmplINS0_11MessageLiteENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEPKcSC_PKT_PNS1_16InternalMetadataEPNS1_12ParseContextE[_ZN6google8protobuf8internal12ExtensionSet23ParseMessageSetItemTmplINS0_11MessageLiteENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEPKcSC_PKT_PNS1_16InternalMetadataEPNS1_12ParseContextE]+0x777): undefined reference to `__memcpy_chk'
/usr/lib/gcc/x86_64-alpine-linux-musl/12.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: /root/go/pkg/mod/github.com/!proton!mail/gluon@v0.14.2-0.20221206104410-725ddb9db68a/internal/parser/lib/Linux/x86_64/libprotobuf.a(stringprintf.cc.o): in function `google::protobuf::StringAppendV(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, char const*, __va_list_tag*)':
stringprintf.cc:(.text+0x66): undefined reference to `__vsnprintf_chk'
/usr/lib/gcc/x86_64-alpine-linux-musl/12.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: stringprintf.cc:(.text+0x114): undefined reference to `__vsnprintf_chk'
/usr/lib/gcc/x86_64-alpine-linux-musl/12.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: /root/go/pkg/mod/github.com/!proton!mail/gluon@v0.14.2-0.20221206104410-725ddb9db68a/internal/parser/lib/Linux/x86_64/libantlr4-runtime.a(ParserRuleContext.cpp.o): in function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > __gnu_cxx::__to_xstring<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char>(int (*)(char*, unsigned long, char const*, __va_list_tag*), unsigned long, char const*, ...) [clone .constprop.0]':
ParserRuleContext.cpp:(.text+0x18e): undefined reference to `__vsnprintf_chk'
/usr/lib/gcc/x86_64-alpine-linux-musl/12.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: /root/go/pkg/mod/github.com/!proton!mail/gluon@v0.14.2-0.20221206104410-725ddb9db68a/internal/parser/lib/Linux/x86_64/libantlr4-runtime.a(Recognizer.cpp.o): in function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > __gnu_cxx::__to_xstring<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char>(int (*)(char*, unsigned long, char const*, __va_list_tag*), unsigned long, char const*, ...) [clone .constprop.0]':
Recognizer.cpp:(.text+0x2ce): undefined reference to `__vsnprintf_chk'
/usr/lib/gcc/x86_64-alpine-linux-musl/12.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: /root/go/pkg/mod/github.com/!proton!mail/gluon@v0.14.2-0.20221206104410-725ddb9db68a/internal/parser/lib/Linux/x86_64/libantlr4-runtime.a(RuleContext.cpp.o): in function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > __gnu_cxx::__to_xstring<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char>(int (*)(char*, unsigned long, char const*, __va_list_tag*), unsigned long, char const*, ...) [clone .constprop.0]':
RuleContext.cpp:(.text+0x2ce): undefined reference to `__vsnprintf_chk'
/usr/lib/gcc/x86_64-alpine-linux-musl/12.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: /root/go/pkg/mod/github.com/!proton!mail/gluon@v0.14.2-0.20221206104410-725ddb9db68a/internal/parser/lib/Linux/x86_64/libantlr4-runtime.a(ATNState.cpp.o):ATNState.cpp:(.text+0x10e): more undefined references to `__vsnprintf_chk' follow
/usr/lib/gcc/x86_64-alpine-linux-musl/12.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: /root/go/pkg/mod/github.com/!proton!mail/gluon@v0.14.2-0.20221206104410-725ddb9db68a/internal/parser/lib/Linux/x86_64/libantlr4-runtime.a(MurmurHash.cpp.o): in function `antlr4::misc::MurmurHash::update(unsigned long, void const*, unsigned long)':
MurmurHash.cpp:(.text+0x12f): undefined reference to `__memcpy_chk'
collect2: error: ld returned 1 exit status

make: *** [Makefile:104: proton-bridge] Error 2
```

## Steps to Reproduce

1. Download with gh utility onto Alpine 3.17.1
2. run `make build-nogui` in root directory

## Version Information
HEAD

**Comment by LBeernaertProton** [comment] 2023-01-17 09:36
Duplicate of #333

**Closed by LBeernaertProton** 2023-01-17 09:36 UTC
