### ISSUE TITLE
Multiple instances for one account?

### ISSUE THREAD

**Issue by chiraag-nataraj** [ProtonMail/proton-bridge#69] opened 2020-09-06 20:44 UTC
Because there is no official app for the PinePhone as of now, I [built](https://www.reddit.com/r/PinePhoneOfficial/comments/il8dlg/able_to_compile_protonmail_bridge_on_the/) the Bridge on the phone and it works well! However, I already run the Bridge on my laptop and it suddenly got logged out. Is the Bridge supposed to only be limited to one device per account? I know it's possible to use multiple accounts in one Bridge instance, but is it possible to use multiple Bridge instances (on different devices) for one account?

**Comment by horejsek** [comment] 2020-09-07 06:13
It is possible to use ProtonMail account on multiple devices. Each login has own session. The disconnection was done probably because of either long time without a connection, or deleting session on the server side (you can do that in webapp), or caused by bug from earlier Bridge version which should be fixed in the latest version 1.3.3.

**Closed by horejsek** 2020-09-07 06:13 UTC
