### ISSUE TITLE
Mostly-duplicate emails are not sent

### ISSUE THREAD

**Issue by ericLemanissier** [ProtonMail/proton-bridge#161] opened 2021-01-26 09:26 UTC
When sending several emails to the same recipient, with the same subject and same body, within a short time frame (eg 20 seconds), only the first one is received, and saved in the sent folder.
One could say it is not a bug, but a feature, to filter identical emails, but the problem is that the presence of different attached files does not disable this filtering.

## Expected Behavior
all emails should be received by the recipient, and saved in the sent folder of the sender

## Current Behavior
Only the first email is received by the recipient, and saved in the sent folder of the sender

## Possible Solution
Workaround: modifying the subject of the email
Not a workaround or solution, but doing the same from the webmail results in all emails being properly received and saved in the sent folder

## Steps to Reproduce
send several emails to the same recipient, with subject "test" and body "test" 

## Version Information
protonmail bridge 1.5.7
client: outlook and thunderbird
bridge: running on windows and linux

## Context (Environment)
A scanner is sending scanned documents by email via the protonmail bridge, so usually it sends several emails in a row to the same recipient, with the same subject and body, but different attached files.

## Detailed Description
Don't filter sent emails based on similarities ?

**Comment by jameshoulahan** [comment] 2021-01-26 11:31
Hi @ericLemanissier, thanks for the report.

Indeed, we employ a hashing system to prevent certain mail clients from sending the same message multiple times within a short timeframe. Messages with identical hash are considered duplicates. The hash takes into account, among other things, attachment name, MIME type, and size.

I'm slightly confused about what you're experiencing:
- you write `but the problem is that the presence of different attached files does disable this filtering` --> this is expected, as differing attachments usually lead to differing message hash. 
- you then write `so usually [the scanner] sends several emails in a row to the same recipient, with the same subject and body, but different attached files` --> from this, one could infer that the different attached files are *not* leading to differing message hashes.

Could you please clarify exactly what is happening?

In general, as the hash only takes into account attachment name, mime type and size, there is a chance that two otherwise identical messages, which have attachments that differ only in data (but not name/type/size), could be considered identical. This should be considered a bug; I'll open an internal issue to take into account attachment data too.

**Comment by ericLemanissier** [comment] 2021-01-26 11:37
Thanks for answering. What I wanted to write is "but the problem is that the presence of different attached files does NOT disable this filtering".
May I suggest adding the message date to the hash ?

**Comment by jameshoulahan** [comment] 2021-01-26 11:46
Including time in the hash sort of defeats the purpose of the hash since we aim to prevent duplicate messages *within a certain timeframe* from being sent.

> the presence of different attached files does NOT disable this filtering

this sounds like the different attachments differ only in data, but have identical names/content-types/sizes? If attachment data itself was part of the hash, would that resolve your problem?

**Comment by ericLemanissier** [comment] 2021-01-26 12:07
hashing the content of attached files should work, but I do not agree that hashing the date of the email defeats the purpose of the filtering, because the Date attribute is generated by the email client at the time the message was edited by the user (as opposed to the time it was sent to the SMTP server)

**Comment by jameshoulahan** [comment] 2021-01-26 12:21
You are correct, I took a quick look at the code and we take the date from the message header, which should be constant across repeated send attempts.

I'll suggest both solutions to the team (attachment data, date); let's see what we come up with. Thanks!

**Comment by ericLemanissier** [comment] 2021-03-12 08:57
friendly ping @jameshoulahan is there some news on this issue?

**Comment by jameshoulahan** [comment] 2021-03-12 10:08
No progress on this yet. The issue is in our backlog but internal priorities were reshuffled a bit and as such I can't promise a resolution to this any time soon.

**Comment by andrzejsza** [comment] 2022-10-24 10:54
update for internal reference - GODT-1777

**Comment by andrzejsza** [comment] 2023-02-28 01:15
we consider the issue fixed with 3.x - closing.

**Closed by andrzejsza** 2023-02-28 01:15 UTC
