### ISSUE TITLE
New version of bridge fetches huge amount of data

### ISSUE THREAD

**Issue by frozencemetery** [ProtonMail/proton-bridge#243] opened 2021-12-17 18:35 UTC
When launching proton-bridge at 27e7d7967d03a47f51b0687354c66dc4643a2dfb, it now fetches a huge amount of data on start - logs suggest it's downloading every message and storing it on disk.

## Expected Behavior

I'm already using bridge to download messages to this machine - there's no need for bridge to store an additional copy.

## Current Behavior

Since what I'm guessing is 6bd073901381a15f8e8ca2ea374f36a1d5b2ebd9, hundreds of megs of encrypted blobs are fetched and stored in ~/.config/protonmail

## Possible Solution

If, as it seems, this is intentional, maybe an option to turn it off?  Otherwise it seems like this is going to eat as much disk as one has quota in protonmail.

## Steps to Reproduce

1. Have decent sized mailbox and run bridge at b0ce46ca8a84e6f51360237ae906990a2b52f5dd.
2. Upgrade bridge to 27e7d7967d03a47f51b0687354c66dc4643a2dfb

## Version Information

27e7d7967d03a47f51b0687354c66dc4643a2dfb (looks like this will become 2.0.1).  It presumably happened earlier, but it's hard to test.

## Context (Environment)

Linux, built from git, running headless.  Email is pulled over IMAP for use with another client.  This is a single machine setup, so the other client stores a copy and so does bridge.

## Detailed Description

I'd like bridge to not store all this on disk, but as it seems intentional, perhaps an option to turn this behavior off?

## Possible Implementation

I don't write Go and am not very familiar with the tree, sorry.

**Comment by andrzejsza** [comment] 2021-12-17 20:31
yes, this is very much by design - Bridge now stores encrypted message bodies to be able to serve them to the client faster. yes, you can switch this off - go to Settings/Advanced settings/Local cache - you can disable it there.

**Comment by frozencemetery** [comment] 2021-12-20 20:20
Ah, and I see it's `cache_enabled` in ~/.config/protonmail/bridge/prefs.json (I run headless).  Thanks!

**Comment by tomtastic** [comment] 2022-03-03 14:12
This does seem to be an issue, I was just doing an initial setup/sync of my ~600MB account and Bridge has downloaded over 20GB since it began.

**Comment by tomtastic** [comment] 2022-03-04 16:47
I tried disabling the cache and re-syncing from scratch, but it didn't make any difference, still ridiculous amounts of data downloaded and Apple Mail was struggling to send even a single email, and selecting an un-synced email would often simply timeout.

I've now reverted to Bridge v1.8.12 where this behaviour doesn't seem to exist (almost fully synced and just 1.2GB of data in total, vs the 20GB+ previously), and the end user experience with Apple Mail is _far_ more responsive.

Checking the logs over a similar hour long period of syncing as before, indicates that v1.8.12 is requesting a GETs of unique items an order of magnitude less often.

```
$ head -1 v1.8.12_b0ce46ca8a_1646408253.log; tail -1 v1.8.12_b0ce46ca8a_1646408253.log
INFO[Mar  4 15:37:33.781] No need to migrate file, source doesn't exist  destination="/Users/tmatoo/Library/Application Support/protonmail/bridge/prefs.json" source=/Users/tmatoo/Library/Caches/protonmail/bridge/c11/prefs.json
INFO[Mar  4 16:39:13.850] Requesting GET /mail/v4/messages/Vn8lAo54CkVv4X5CDa44OY25WgCENNB1yFTZIEwuB5_wHa9z7oQhUtKM2wNq3EHFb77rDHHsgzf4Rb36q1ruiA==  pkg=pmapi
```
```
$ grep '/mail/v4/messages' v1.8.12_b0ce46ca8a_1646408253.log| cut -d" " -f5- | sort | uniq -c | sort -n | tail -10
   3 Requesting GET /mail/v4/messages/vG_cmx-uACM2vpSMVxUo0WmQvhaNMxDopPuNr3ek2bNAnAV4VSzaLNBMuxJak3M6dTNTytLTR4muQn2-kv6tAA==  pkg=pmapi
   3 Requesting GET /mail/v4/messages/wtcXFIRWdYbb9ZqYVuWQXDHqwmAGjOWwvdLsprLjXIQ7peO4_3fbHkjMtJiQ9pWL0w9uMGX8Ljp36LeJ2c3l6A==  pkg=pmapi
   4 Requesting GET /mail/v4/messages/9SWYPYzSQ6sZHG4gBcegGOz3FOjMyB6VSG4Y5TMEZMb935gsA5GiirdZ9mWGI-9yYEYGHPkU0afPKYx5W7OSsA==  pkg=pmapi
   4 Requesting GET /mail/v4/messages/IqR8tKcOW8DU_dB-HguNanWttHj5MJ-uj4VfrueY7LqQnHvk4duQJN9UusIRiRt9d55kmqOEsLhofJx4ZbyU6Q==  pkg=pmapi
   4 Requesting GET /mail/v4/messages/k3HIAdUXDbbkn0nFEgWVNoBuN9zPJSBQBriiff9M3iFKO8hsSvxCBcc2cYp7o3Bgl2rLyUmfhcXu9LuK7QJkIA==  pkg=pmapi
   4 Requesting GET /mail/v4/messages/n7XLqz1ciVDyfcW7qjG-J45wPKa6oPRKkTeFvBaqsgKITzdJ7ifcsU28NtDezM6sVqR5D3YZ9hWr16jMv6_dvQ==  pkg=pmapi
   4 Requesting GET /mail/v4/messages/txiE6RX0T4Dx9eUe_yeBdkpw9hAFTXcjof4EnLNU_BIzN__opQTdjG7sz-YwOwzu-ShqqKo9fN5wAgJUZgnMfA==  pkg=pmapi
   4 Requesting GET /mail/v4/messages/yr07-82RtELnYeKq8urjTs4L-xqsOtUDMh7_VBD6wR_l4ZEKp08czfkIjinxSvBYZGi4vlPBXbR1GrkvA2R4PQ==  pkg=pmapi
   5 Requesting GET /mail/v4/messages/nrbniIHEjJic3b-xsIv3D42Jx7M5kv7FKmJLwgyN-oh4I1RCf2GRw0EMr010dzn4n7BGboN0jUdfO_9CI0dN0A==  pkg=pmapi
  30 Requesting GET /mail/v4/messages              pkg=pmapi
```
```
$ grep '/mail/v4/att' v1.8.12_b0ce46ca8a_1646408253.log| cut -d" " -f5- | sort | uniq -c | sort -n | tail -10
   3 Requesting GET /mail/v4/attachments/sFrJLgpRJtcmGxQgckPKdlgPWw7T2jDaBxyanMPJvXOzctVzOqjAvqmo8dORxalrewRczb3egX9rz5WoIH1sFw==  pkg=pmapi
   3 Requesting GET /mail/v4/attachments/uK6agRJkbustf8KvP-I-fJTgu7vmXDlNKv4F4W0ju9UqpAt9gciZ9DAEdAodN5Hmc2uspsgjiemRB2OSmAG6Kw==  pkg=pmapi
   3 Requesting GET /mail/v4/attachments/zahuHHiiNXuIhhJfbO97lNe9onDOHI0PLZzzkF5fX3LEYz3VKUyncZumMrFT3lDlrqIKKVfmBoKgHwNhqcsO4g==  pkg=pmapi
   4 Requesting GET /mail/v4/attachments/26D4uTDAnnoDyqrT1qKLF_weKpsmaJNkWyR1FHaS1rXflSS0Vly8GNKyZxW1UzxYoUZeuF5Bv6hAXBWzDMS0_g==  pkg=pmapi
   4 Requesting GET /mail/v4/attachments/9um1UE3iRELdkVBDXWqliBrdeKs03oSS_XNOU1hS52gnUfUq-_v7JxfHLztOxPR_bPQjLFBhGS31Rfu1NntPow==  pkg=pmapi
   4 Requesting GET /mail/v4/attachments/O0DXF6Ub69XVTmewDV511F2KveFk_Nhu832Dxhqk9344jFBBBot2SCy3JyMtwtqmSVCztQAXreBeg1Bq3LRV_g==  pkg=pmapi
   4 Requesting GET /mail/v4/attachments/dw-UHZojI5BIqjxJuJ765IzWqh4etrjWgBWarWVU5YGPqAfKMZmxlcFKAqZoICv9Fm1sv7AX1N81r9XUM7eGdg==  pkg=pmapi
   4 Requesting GET /mail/v4/attachments/p5vwSJbrxWbPIdYV-wJg2bZ-wdUa_oL2eYImwg8d4J_Clg3SQXqJLXh56Fa1KbEGftOCLhapqGxb568k27B8TA==  pkg=pmapi
   4 Requesting GET /mail/v4/attachments/sIwp3vxj61OZQkm3s6a-XFbmUilxjKT_CABIyCkcRVSD-2ZejuSjw9VzRegpurkvgZpOGC0uXa-ziv3vZuUE4g==  pkg=pmapi
   4 Requesting GET /mail/v4/attachments/vxF5ZV1gmLaA_akAsuURstF5w2KqS7mvQ72fr9UHz-HDbExXEBSiU_T7O0sfPuTxdXU5GqgwuhPR9WbqnG4hJw==  pkg=pmapi
```
```
$ grep '/event' v1.8.12_b0ce46ca8a_1646408253.log| cut -d" " -f5- | sort | uniq -c | sort -n | tail -10
   1 Requesting GET /events/latest                 pkg=pmapi
   2 Requesting GET /events/IOpbr1v8OODM_JRS9tgB-H00qfo5K0vE28KFh19tUXWR1zYgT10MM57TcYrJ8NP3qk-ZpGgni3uNnhjD1GFq6w==  pkg=pmapi
   2 Requesting GET /events/ZP1DrCs9rJMOzrSJz1dbrbhkvSzNomBXF3N67YHs2bzz4IYiZXZNwF5AJ4VVkNSUT1PJLVHTIFE1NaKcwVOVwQ==  pkg=pmapi
   6 Requesting GET /events/LEEkbBu__byiCe1LgH6jg8erwORJZh1uKXwuzvY9k21lzeMoEcvdDc9GgTrZFqWq3gwWKI-yK3g0lh0oUOQ0vA==  pkg=pmapi
   6 Requesting GET /events/S19Mv-10ul4GzYUrBoxBjBhLk4e3wpwPYEhvkHVowwkM5puOrAjigLG_rAYWDIJ-zRcWZuWkKnKPYZmPh4bRwQ==  pkg=pmapi
   7 Requesting GET /events/Wtqohxyn7Da7HeR2AQjB9hCsbqvJMgWwjrYDrBJ1b57fyEcvFfdawarBm8-33exrhPPlV-W7Z4KXeOFc-37yiQ==  pkg=pmapi
  10 Requesting GET /events/HkvJk4Lbg6FTsSjqIKR-Rk6fDwY3k4kOR0UiMN5Y8hBEK6gMwFhUsyTv8AHtVj45MWsp9PaCQmoqAGI2buFq5g==  pkg=pmapi
  11 Requesting GET /events/LzYKC64TEkyESV4j58EMVx8vRMOKUOF3bv78oDvDd36ziwYmUQk4tgODZt_lhbDQHIDNMud1mQMRacFw1lJRcw==  pkg=pmapi
  18 Requesting GET /events/d7vA5EIcWRCoQ2lc7zzlu2gy0bJuyNi-zVllIT66GqEbP7yI5KW4hUy4MNYkgNq4IWSw5XEqyKljMSytes6J1Q==  pkg=pmapi
  40 Requesting GET /events/6Vj3-tIgRt32Vx8vOhjy1acS_XivgL5yp_InXpmLwtj2CGyoumdiK56TjJ3otgVZMZsGZlEBHYNI9M6KFZprHw==  pkg=pmapi
```

**Comment by andrzejsza** [comment] 2022-03-07 13:58
reopening this as we're investigating. we were assuming the excessive traffic comes from client-side, but are now confirming this theory. will keep you posted.

**Comment by ianhundere** [comment] 2022-04-16 14:21
+1 

```
❯ du -sh .config/protonmail/bridge/cache/c11/ | sort
9.1G	.config/protonmail/bridge/cache/c11/
```

**Comment by andrzejsza** [comment] 2023-02-28 01:31
we've completely change the behavior with Bridge v3. closing the issue, it anyone still experiencing unreasonably high network traffic - please get in touch with support for further debugging.

**Closed by andrzejsza** 2023-02-28 01:31 UTC
