### ISSUE TITLE
macOS menubar icon is fuzzy

### ISSUE THREAD

**Issue by tusing** [ProtonMail/proton-bridge#142] opened 2020-12-21 17:35 UTC
The macOS menubar icon looks fuzzy compared to other menubar icons.

## Expected Behavior

The icon should be as sharp and consistent (appropriately sized) as other menubar icons.

## Current Behavior

The screenshot doesn't convey this as clearly, but you can still kind of tell:

<img width="118" alt="Screen Shot 2020-12-21 at 12 33 42 PM" src="https://user-images.githubusercontent.com/1077203/102805125-c4205a80-4388-11eb-901c-1ab6560acc1c.png">

It definitely sticks out in person on the Retina display. 

## Possible Solution

Use vector graphics or a higher resolution icon.

**Comment by andrzejsza** [comment] 2021-04-08 22:06
@tusing the problem is not with the icon itself (it has the right size and resolution) but with Qt that we use for GUI. We're testing the solution right this moment.

**Comment by andrzejsza** [comment] 2021-05-17 12:37
fixed in 1.8.0 (currently only early access, will be rollout to stable later this week).

**Closed by andrzejsza** 2021-05-17 12:37 UTC
