### ISSUE TITLE
Xfce, v2.0.1 menu doesn't work if status tray plugin "Menu is primary action" is enabled

### ISSUE THREAD

**Issue by ghost** [ProtonMail/proton-bridge#241] opened 2021-12-17 01:09 UTC
## Expected Behavior
Clicking the icon in the status tray should bring up the app menu

## Current Behavior
Clicking the icon does nothing

## Possible Solution
2.0.1 behaves differently from previous versions, in that right-clicking the icon brings up Status Tray Plugin's right-click menu, even if "Menu is primary action" is unchecked. No other apps I have tray icons for behave this way, so this might be related.

## Steps to Reproduce
1. Be using Xfce panel with Status Tray Plugin
2. In Status Tray Plugin options, enable "Menu is primary action"
3. Run Bridge v2.0.1
4. Left-clicking on the tray icon does nothing

## Version Information
v2.0.1

## Context (Environment)
Can't bring up the Bridge window unless I change my settings. The window can be opened by re-running the app from whisker menu, but that's inconvenient. It's also not possible to quit the app without being able to access the app's menu.

**Comment by Ammako** [comment] 2021-12-19 23:41
Okay, this happens because what the "Menu is primary action" option does, is to take whatever the right-click action is, and make it the left-click action. Then right-click just becomes the Status Tray Plugin right-click menu.

The problem is that v2 bridge doesn't have a menu on right-click, it has no actions at all mapped to it. So when "Menu is primary action" is enabled, you lose the primary left-click functionality, without there being any right-click functionality to replace it.

**Comment by LBeernaertProton** [comment] 2023-04-14 13:19
Closed as this issue related to v2.x which is no longer supported. If anyone else is experiencing this problem, please feel free to-reopen.

**Closed by LBeernaertProton** 2023-04-14 13:19 UTC
