### ISSUE TITLE
very slow local sync

### ISSUE THREAD

**Issue by jknockaert** [ProtonMail/proton-bridge#391] opened 2023-05-25 07:39 UTC
Am using bridge v3.1.3 on macOS 13.4.
On my laptop I use MailMate as IMAP client. With bridge fully synced it takes MailMate between 5 and 10 minutes to do a local sync against bridge even when there aren't any new messages. That's a bit on the slow end of things. There may be a relation with #354. I have about 100 folders.
I am somehow suspecting that it may be the gluon database that is missing an index. I have been peeking into the bridge files and managed to open a .db file with sqlite, so I guess that is what is being used as db backend. Browsing through the tables and looking at the indexes I noticed the absence of any index on `ui_ds(mailbox_ui_ds)` and also `message_flags(message_flags)`, but I may be misunderstanding the database model. Is there any way to log the database queries? That would be helpful to identify potential optimisations.

**Comment by LBeernaertProton** [comment] 2023-05-25 07:47
@jknockaert your suspicions are indeed correct. We are currently working on refactoring the code/database to address the issues reported by #354.  

I will close this ticket as it is basically a duplicate of #354. Please follow that ticket for further updates.

**Closed by LBeernaertProton** 2023-05-25 07:47 UTC
