### ISSUE TITLE
Protonmail Bridge 3.14.0-3 fails to launch on archLinux due to `Qt_6.8' not found

### ISSUE THREAD

**Issue by Cherkah** [ProtonMail/proton-bridge#498] opened 2024-10-13 18:38 UTC
Issue tracker is ONLY used for reporting bugs with technical details. "It doesn't work" or new features should be discussed with our customer support. Please use bug report function in Bridge or contact bridge@protonmail.ch.

after the last protonmail update i'm not able anymore to start the app:

`protonmail-bridge: /usr/lib/libQt6Core.so.6: version `Qt_6.8' not found (required by protonmail-bridge)`

## Expected Behavior
start protonmail bridge in a normal way

## Current Behavior
unable to start the app neither via launcher nor terminal

## Possible Solution
wait for qt6-base lib update:
/usr/lib/libQt6Core.so.6.7.3  -> /usr/lib/libQt6Core.so.6.8

## Steps to Reproduce

1. after laste update
2. reboot
3. restart protonmail
4.

## Version Information

Protonmail Bridge 3.14.0-3

## Context (Environment)

Operating System: EndeavourOS 
KDE Plasma Version: 6.2.0
KDE Frameworks Version: 6.6.0
Qt Version: 6.7.3
Kernel Version: 6.11.3-arch1-1 (64-bit)
Graphics Platform: Wayland

**Comment by Cherkah** [comment] 2024-10-14 22:16
after updating the system with the qt6 V6.8 packages I get the error: could not load QML component.
see the attached gdb log file.
[protonMail_gdb.log](https://github.com/user-attachments/files/17369815/protonMail_gdb.log)

ps. after reporting the qt6 library problem, less than 2 hours after reporting the qt6 library problem another protonbridge update solved the problem so thanks for that to the protonmail devs for their responsiveness

**Comment by Cherkah** [comment] 2024-10-15 08:17
ok thanks. as you said the issue has already been reported an people are working on it.

**Comment by Antiz96** [comment] 2024-10-15 09:02
Hi,

This was indeed an issue with Arch Linux specifically, not related to ProtonMail Bridge upstream at all.

However, we are facing another issue running ProtonMail Bridge with Qt6.8 (but this is a separate issue). It has been reported [here](https://gitlab.archlinux.org/archlinux/packaging/packages/protonmail-bridge/-/issues/3) on Arch side.  
We are currently analyzing the cause and we'll report that properly to upstream if needed :)

@Cherkah, can you please close this issue so we don't create useless noise for ProtonMail Bridge developers (since this issue specifically was an Arch one and not a ProtonMail Bridge one)?

As said above, if we need to fill a bug report to this repo regarding the other / unrelated Qt6.8 issue we're currently facing, we'll do it ;)

**Closed** 2024-10-15 20:59 UTC
