### ISSUE TITLE
Does not work natively on Apple Silicon ARM M1 Macs

### ISSUE THREAD

**Issue by paulmillr** [ProtonMail/proton-bridge#155] opened 2021-01-15 22:32 UTC
## Expected Behavior

Current mac build is x86-only. It would be great to have universal binary with support for ARM cpus.

## Current Behavior

Does not work on ARM cpus unless Rosetta is installed

## Possible Solution

Install Rosetta

## Version Information

1.5.4

**Comment by jameshoulahan** [comment] 2021-01-18 07:45
We agree, but this is not possible yet:
- we need to wait for golang 1.16, which will include support for apple's 64bit arm chips
- we need to wait for Qt support for it (which only arrived in Qt 6.1 I believe)
- we need to wait for therecipe's golang Qt wrapper to support Qt 6.1 (currently only supports up to 5.15 I believe)

We intend to support apple's new architecture when it's possible to do so but as this is not something we can "fix" from our side yet, I will close this issue.

**Comment by paulmillr** [comment] 2021-04-08 03:50
@jameshoulahan hey, a quick heads up. The upcoming Macos version would [disable](https://9to5mac.com/2021/03/02/apple-may-disable-rosetta-2-on-m1-macs-in-some-regions-macos-11-3-code-suggests/) Rosetta in some regions due to patent issue.

Which will make proton-bridge unusable on new macs in a few weeks. I think this should be reprioritized. Go 1.16 is out, QT 6.1 would be out in 2 weeks. Therecipe didn't do any commits since september, so you will need to fork it.

**Comment by jameshoulahan** [comment] 2021-04-13 08:51
@paulmillr thanks for the heads up! We're looking into options now.

**Comment by paulmillr** [comment] 2021-06-12 07:53
@jameshoulahan any updates on this? Qt 6.1 was out one month ago, Go 1.16 was published in February. Therecipe's wrapper seems to be dead.

**Comment by paulmillr** [comment] 2021-07-12 15:29
@jameshoulahan this should be straightforward. All versions have been released and are stable.

**Comment by paulmillr** [comment] 2021-07-12 15:29
Can you re-open the issue? Because right now it's something you *can* fix from your end.

**Comment by andrzejsza** [comment] 2021-07-12 17:00
@paulmillr this is work in progress - for internal reference GODT-1170. Will update this tickets once we confirm working solution.

**Comment by paulmillr** [comment] 2021-07-12 20:10
Awesome!

**Comment by alxdrlitreev** [comment] 2021-07-19 12:12
@andrzejsza @jameshoulahan hi guys, any updates on this issue?

**Comment by andrzejsza** [comment] 2021-07-27 15:06
it's been painful. because of therecipe, we need to compile Qt 5.13.0 by ourselves. still work in progress.

**Comment by paulmillr** [comment] 2021-09-10 04:17
@andrzejsza how much work is needed now?

**Comment by paulmillr** [comment] 2021-09-10 18:52
Can this get re-prioritized? It has been more than 1 years since ARM testing machines appeared. 

It is **not possible** to remove Rosetta 2 x86 emulator on ARM Macs once it's installed. Unofficially, you can do it by disabling your System Integrity Protection which is itself a bad idea. But not in an official way.

Why would Proton force its users to install x86 emulator and expose themselves to x86 malware, which is much more popular than ARM-compiled malware?

**Comment by kebian** [comment] 2021-11-02 14:17
Any news on this?  Protonmail bridge is the only intel application I have to run now.

**Comment by andrzejsza** [comment] 2021-12-04 14:41
sorry guys, it's not forgotten but has not been a priority. hoping to get back to this in the coming weeks, will keep you posted when progress is made.

**Comment by wasabinator** [comment] 2021-12-05 02:25
I pulled the repo and took a look myself, and it appears that there is going to be a roadblock with Qt itself, which in turn affects the go binding lib being used (ref: https://github.com/therecipe/qt/issues/1248).  Qt currently only has preliminary M1 support in their 6.2 version, but this repo I believe will currently be depending on 5.13 due to the use of the golang qt binding.  It can apparently be bumped to 5.15 and then a short term solution can be used to get Qt building on M1, but I doubt anyone would be considering that "production ready" with something as security focused as ProtonMail...

**Comment by andrzejsza** [comment] 2021-12-06 10:12
thanks for looking into this. indeed - the only way for us at this moment is to compile qt 5.13 ourselves.

**Comment by paulmillr** [comment] 2021-12-26 11:38
@wasabinator 

> Qt currently only has preliminary M1 support in their 6.2 version

Why is that? The official blog post says:

>Qt 6.2 fully supports macOS on Apple Silicon. Qt now makes it easy to create universal binaries and to develop for macOS on both Intel and Apple Silicon. It has always been possible to run Qt applications on Apple silicon via the Rosetta layer, but Qt 6.2 now provides full support to run natively on the Apple silicon. 

Is there a lot of work in updating to qt 6? Is it backwards-incompatible, much?

**Comment by paulmillr** [comment] 2022-01-06 01:55
Signal Desktop just got an ARM update. I've tested it on mac with Rosetta and it's like five times faster after they dropped x86 rosetta emulation.

Would be great if the same thing was done to Proton. Proton remains the only app that requires x86 and i'll probably stop using it for now, because installing Rosetta doesn't cut it.

Could you folks focus on ARM? You'll need to upgrade QT sooner or later anyway.

**Comment by andrzejsza** [comment] 2022-01-07 07:39
@paulmillr qt 6 doesn't support the Recipe anymore, so yes, an update is not that straightforward - but we would like to have it done anyway.
what do you mean by five times faster? what are you measuring?
yes, we'll look into this properly as soon as V2 is out in stable production.

**Comment by paulmillr** [comment] 2022-01-07 10:09
@andrzejsza I mean my personal ui feelings. Scrolling, typing, etc. if feels much faster without emulation. It's much much faster and eats much less of cpu

**Comment by vol24pl** [comment] 2022-01-15 14:34
Bridge is a paid option and one of the only reasons that I have a subscription.

If it has a hard dependencies on QT, can you just distribute a Mac binary of the CLI version with homebrew?

**Comment by andrzejsza** [comment] 2022-02-01 12:48
just a quick update here - therecipe is the blocker. we tried to compile it ourselves but there were too many issues. the only way forward is to abandon therecipe completely; this would allow us to simply update to qt 6.x.
it's a few weeks work - will let you know once we get there.

**Comment by yieldchan** [comment] 2022-02-15 23:32
> If it has a hard dependencies on QT, can you just distribute a Mac binary of the CLI version with homebrew? If someone's into distinguishing cpu architectures in the apps, I guess they are tech savvy enough to be content with the CLI version.

Something like this would be cool if it's not too much effort. Would be interesting to see battery impact.

**Comment by zmre** [comment] 2022-03-13 20:08
I'd frankly be happier without the GUI, particularly if it came bundled up with a homebrew service and cli. That option seems like a good intermediate point with low work and little downside.

**Comment by macbugs** [comment] 2022-03-23 00:39
> _**it's a few weeks work - will let you know once we get there**_

I would not complain about how long it takes -- but I will say the [build instructions page](https://github.com/ProtonMail/proton-bridge/blob/master/BUILDS.md) should include some kind of notice, like **_"does not build on Apple ARM"_** so people do not spend the time to configure & build this only to find that the output is an Intel application.

**Comment by andrzejsza** [comment] 2022-03-30 23:00
@macbugs, yep, done now.

**Comment by AwlsomeAlex** [comment] 2022-05-13 20:00
@andrzejsza If I understand correctly, the issue is with the QT bindings. Does Proton have any plans to change to a new library (since this one has been stale since 2020), perhaps [Fyne](https://github.com/fyne-io/fyne)?

**Comment by paulmillr** [comment] 2022-05-17 03:39
How are we doing? It has been more than 1.5 years since the initial release of M1 macs and Protonmail still hasn't released anything.

Again, installing Rosetta can be a no-go solution for one simple reason: you cannot uninstall it. It exposes your machine to x86 malware forever. 

It's a huge shame that the simple feature that's only available for paying customers is being neglected.

**Comment by ljanyst** [comment] 2022-05-31 20:50
Check this out https://github.com/ljanyst/peroxide It's meant for Linux, but works fine on my M1 Mac after adjusting the paths in the config file.

**Comment by ljanyst** [comment] 2022-05-31 22:21
I think also the regular proton bridge builds fine on M1 without the GUI mode.

**Comment by tecandrew** [comment] 2022-07-17 06:42
Of all the apps I have running (even at idle), this app is the top CPU consumer. is there any way this issue can be pushed up? It works fine under Rosetta2, but it would be great if I could not worry about this app taking up everything.

![Screen Shot 2022-07-16 at 11 36 16 PM](https://user-images.githubusercontent.com/21319730/179387084-809d9b97-8410-49cf-be1d-c206cedb0c59.png)

**Comment by andrzejsza** [comment] 2022-07-19 15:14
It is pushed and very much in advance progress - right now we are working on dropping therecipe/qt completely, so that we can upgrade to Qt6. Once done, M1 support will will be very straightforward.

**Comment by paulmillr** [comment] 2022-08-04 01:27
@andrzejsza tell me something I haven't heard. 1.5 years since the issue was created, 2 years since ARM macs were available for testing. What is your timeline?

**Comment by Eroan** [comment] 2022-08-14 15:05
Hi there, any news here ?
Running MacOS for web development, Protonmail Bridge is the last Intel app running on my computer, with an impact over CPU consumpation.
Thanks.

**Comment by luisivan** [comment] 2022-09-06 12:22
This is quite unbelievable. There are some dependencies indeed, but not shipping this in like a year and a half is quite something... specially to your paid customers

**Comment by andrzejsza** [comment] 2022-09-07 22:32
it's not great, yes.
dropping the recipe meant basically rewriting the frontend into a new Qt/QML C++ application, adding a new gRPC service as the binding layer between frontend and the backend and then converting the Go backend to new gRPC based architecture. it was much bigger task than anticipated.
we are in the final alpha stages - we found a few regressions that we still need to fix before public beta release.

**Comment by luisivan** [comment] 2022-09-08 13:30
Thanks for the context @andrzejsza, hoping for an ETA soon!

**Comment by vkuznet** [comment] 2022-09-15 17:05
+1

**Comment by ejl371** [comment] 2022-09-25 20:12
> it's not great, yes.
> dropping the recipe meant basically rewriting the frontend into a new Qt/QML C++ application, adding a new gRPC service as the binding layer between frontend and the backend and then converting the Go backend to new gRPC based architecture. it was much bigger task than anticipated.
> we are in the final alpha stages - we found a few regressions that we still need to fix before public beta release.

I saw in the Apple Mail thread that a beta will be released. next week.  That is exciting news, frustrating it has taken this long, but exciting news.  What's insane is I was running the iPad app on my Mac for a while after side loading it, but then it wouldn't update anymore (which Apple says has to be a developer request), which seems like it would have been a much easier port than the bridge.

**Comment by andrzejsza** [comment] 2022-09-28 11:40
released to beta https://github.com/ProtonMail/proton-bridge/releases/tag/v2.4.0 - feedback welcome.

**Comment by maxdumas** [comment] 2022-09-28 15:10
Hi @andrzejsza. Thanks so much for your hard work on this issue. I've installed the beta version you linked above and it looks like it's having trouble connecting to the new gRPC backend. Upon launching the app, nothing happens for about a 60 seconds and then the following error message appears:

<img width="532" alt="Screen Shot 2022-09-28 at 11 08 24 AM" src="https://user-images.githubusercontent.com/1356764/192815842-f53e47a9-5efc-4aeb-bc63-323811662d8d.png">

I can see the process still idling in the background, in my process list, so I presume it's waiting for a response from the server which it fails to receive.

**Comment by tecandrew** [comment] 2022-09-28 19:01
where do we leave feedback on the Beta? this thread? it worked right-off-the-bat and no longer uses a ton of CPU usage!

**Comment by andrzejsza** [comment] 2022-09-28 19:07
glad to hear. here is good, we want to make sure that beta works for everyone as expected. we'll close the thread once we go to live.

**Comment by klem-everywhere** [comment] 2022-10-05 14:52
CPU usage is much better.
But Apple Mail is still getting my emails a minute or so later than my Proton app on my iOS.
Is this something that would be solved with https://github.com/ProtonMail/gluon?

**Comment by andrzejsza** [comment] 2022-10-05 20:02
@klem-everywhere glad to hear. no, such delay shouldn't be happening at all. are you sure you're client checks for the messages automatically and not on any specified interval?

**Comment by mdibaiee** [comment] 2022-10-24 13:12
I experience the same delay of messages arriving in Apple Mail much later than phone or web clients. This doesn't seem to happen with my gmail account for work. I can't find any option about any interval in Apple Mail configuration, so I suppose it is trying to check messages automatically.

**Comment by klem-everywhere** [comment] 2022-10-24 13:17
> @klem-everywhere glad to hear. no, such delay shouldn't be happening at all. are you sure you're client checks for the messages automatically and not on any specified interval?

Sorry I missed this, as @mdibaiee mentioned, it doesn't have a settings for interval, and I'm using the "Profile" generated by Proton Bridge and not setting up IMAP by myself so all the settings should be correct.

**Comment by andrzejsza** [comment] 2022-10-25 06:47
weird. would you might submitting the ticket to support? we might need to check your logs. just to sanity check, in Apple Mail, go to Preferences -> General -> Check for new messages and make sure it's set to 'Automatically', which indeed it should be default.

**Comment by mdibaiee** [comment] 2022-10-25 07:05
@andrzejsza I did fill a support ticket a week ago, and all they suggested was changing my IMAP ports (changing the initial `1` in both ports to `2`)... which I did but I don't see an improvement. I also checked the configuration you just mentioned, it is set to Automatically.

**Comment by tecandrew** [comment] 2022-10-27 02:31
> **EDIT:** Apologies, this appears to have been an issue with my VPN on my end and is now resolved.
> 
> Hi @andrzejsza. Thanks so much for your hard work on this issue. I've installed the beta version you linked above and it looks like it's having trouble connecting to the new gRPC backend. Upon launching the app, nothing happens for about 60 seconds and then the following error message appears:
> 
> <img alt="Screen Shot 2022-09-28 at 11 08 24 AM" width="532" src="https://user-images.githubusercontent.com/1356764/192815842-f53e47a9-5efc-4aeb-bc63-323811662d8d.png">
> 
> I can see the process idling in the background during those 60 seconds, in my process list, so I presume it's waiting for a response from the server which it fails to receive. The process exits after closing this dialog.

this occurred to me after updating macOS to Ventura. problem went away after a few tries of relaunching the app. strange...

**Comment by ejl371** [comment] 2022-10-29 20:14
Hi.  The beta bridge works great for me for the most part.  One issue I'm having is that often, the bridge won't reconnect after sleeping the machine.  I have to shutdown the bridge and restart it to get it to reconnect.  Anyone else seeing this?

**Comment by andrzejsza** [comment] 2022-11-23 00:01
and after long beta finally released to live. closing the issue. @ejl371 nothing that we've got any reports on - feel free to open a new issue with more info or contact support so that we can debug. thanks.

**Closed by andrzejsza** 2022-11-23 00:01 UTC

**Comment by mspanc** [comment] 2023-01-07 11:27
@andrzejsza I have just downloaded the newest version of the bridge, and it still runs as Intel code. Are you sure this is fixed?

**Comment by mspanc** [comment] 2023-01-07 11:32
Ok, got it, it's only on GitHub, sorry for bothering.

**Comment by andrzejsza** [comment] 2023-01-08 15:58
yep, not just github but in beta also for now. will be released to live with v3.

**Comment by kklem0** [comment] 2023-01-08 22:45
> yep, not just github but in beta also for now. will be released to live with v3.

Can't wait :)
