### ISSUE TITLE
KDE Wallet Integration

### ISSUE THREAD

**Issue by emileturcotte** [ProtonMail/proton-bridge#68] opened 2020-08-31 02:23 UTC
I run on OpenSUSE using KDE as my desktop and everytime I boot into a new session, I need to provide a password for both gnome-keyring and kwallet. It would be great if the bridge could integrate with the KDE Wallet subsystem instead of being restricted to gnome-keyring.

# Env

OpenSUSE Tumbleweed + KDE
ProtonMail Bridge v1.3.3

**Comment by barthr** [comment] 2020-09-02 16:17
Related: #14

**Comment by jameshoulahan** [comment] 2020-09-08 07:49
Hi and thanks for the feedback. I agree this would be a nice feature.

Bridge uses the [docker-credential-helpers](https://github.com/docker/docker-credential-helpers) open source library for its keychain integration. This provides us access to keychains using the [Secret Service DBus API](https://specifications.freedesktop.org/secret-service/latest/) This API was originally intended to unite the gnome-keyring and KDE wallet projects (see the authors of the draft). Gnome-keyring finished its secret-service support but KWallet's support is still [ongoing](https://community.kde.org/images.community/9/9e/Akademy-bof-presentation.pdf).

We hope to support KWallet at some point in the future.

As this is a duplicate of #34, which was already closed in favour of the more generic issue #14, I will close this issue too.

**Closed by jameshoulahan** 2020-09-08 07:49 UTC
