### ISSUE TITLE
Impossible to build because github.com/myesui/uuid is vanished

### ISSUE THREAD

**Issue by proletarius101** [ProtonMail/proton-bridge#163] opened 2021-01-29 18:14 UTC
Issue tracker is ONLY used for reporting bugs with technical details. "It doesn't work" or new features should be discussed with our customer support. Please use bug report function in Bridge or contact bridge@protonmail.ch.

It's impossible to do a `make build` now because one of the dependencies github.com/myesui/uuid is 404. And github.com/myesui was register 7 days ago?!

## Expected Behavior

It builds

## Current Behavior

````
❯ make build
/usr/bin/go
go install -v -tags=no_env github.com/therecipe/qt/cmd/...
go: github.com/myesui/uuid@v1.0.0: reading github.com/myesui/uuid/go.mod at revision v1.0.0: unknown revision v1.0.0
make: *** [Makefile:150: prepare-vendor] Error 1
````
## Steps to Reproduce

1. Clone this repo
2. make build

**Comment by jameshoulahan** [comment] 2021-02-01 09:41
Hi! This is caused by a problem in a dependency chain. We depend on `github.com/ProtonMail/go-apple-mobileconfig`, which now points to `github.com/emersion/go-apple-mobileconfig` (and is archived), which depends on `github.com/twinj/uuid`, which depends on `github.com/myesui/uuid`, which seems to have disappeared. The upcoming bridge release no longer depends on any of these packages and as such builds correctly. These changes will appear in this repository in due time.

Until then... if you want to get hands-on with the code, you can force bridge to build against a patched version of `github.com/ProtonMail/go-apple-mobileconfig`, in which you switch the uuid implementation over to`github.com/google/uuid` (which is what the upcoming version of bridge uses).

**Comment by andrzejsza** [comment] 2021-02-17 13:21
this is now fixed as per the above comment.

**Closed by andrzejsza** 2021-02-17 13:21 UTC
