### ISSUE TITLE
Can't run MailBridge under two Mac profiles concurrently

### ISSUE THREAD

**Issue by picree** [ProtonMail/proton-bridge#328] opened 2023-01-07 01:43 UTC
Mac 12.6.  Unable to run PMB at the same time for two different Mac users.  The error, "An orphan instance of bridge is already running.  Please terminate it and relaunch the application." is shown.  This is even after changing the default ports for one of the user accounts.

**Comment by LBeernaertProton** [comment] 2023-01-17 10:05
Hey @picree a fix for this issue is available in the v3.0.10 beta release.

**Comment by picree** [comment] 2023-01-18 01:53
Thanks.  It took a bit of effort to make 3.0.10 work.  I have two Mac users and I am trying to run split mode in ea.  Reset PMB in both users.  Uninstalled PMB (and all plists for both users).  Removed PMB profiles.  Rebooted.  Reinstalled PMB.

Trying to set up PMB for the second user produced port errors.  I finally had to change the IMAP port for first user and the SMTP port for the second user (trying to change both IMAP/SMTP for the same user caused PMB to complain, "Port in use" and halt with a greyed out "Save" button.  Seems to be working now but also seems fragile.  I'm afraid to reboot or logout.

**Comment by gabor-meszaros** [comment] 2023-01-30 18:47
Hi @picree, Thank you for reporting this issue. I have just checked our latest alpha build, and I could not reproduce "_"Port in use" and halt with a greyed out "Save" button_" issue. As soon as it is released to beta, you can take a look at it. If it doesn't work, please open a separate issue for that.
Regarding the original problem, it has been fixed, so I am closing this issue. Thank you again.

**Closed by gabor-meszaros** 2023-01-30 18:47 UTC
Labels: bug
