### ISSUE TITLE
"All Mail" folder not behaving correctly

### ISSUE THREAD

**Issue by al101uk** [ProtonMail/proton-bridge#403] opened 2023-07-04 14:13 UTC
Using Proton-bridge along with Thuderbird, when I delete mail and empty trash it is not removed from the "All Mail" folder. I cannot (and should not) delete directly from the "All Mail" folder. I've seen this issue reported numerous times before as "can't delete from "All Mail"" folder, which I think is misrepresenting the issue.

## Expected Behavior
I assume from previous reports that "All Mail" is intended to show mail from all other folder (inbox, trash etc.), when mail is completely removed from all other folders it should also dissapear from "All Mail".

## Current Behavior
Mail is deleted and trash is emptied using Thunderbird, but the mail remains in the "All Mail" folder and cannot be removed.

## Steps to Reproduce
1. Use Proton-Bridge and set up with Thunderbird mail client.
2. Send email to the email address
3. Email should be visible in inbox and "All Mail"... delete email.
4. Email should be visible in trash and "All Mail"... empty trash.
5. Email should no longer be available, but is still visible in "All Mail" where it remains forever and cannot be removed.

## Version Information
Proton-Bridge 3.3.0 and Thunbderbird 102.12.0

The temporary workaround I have found for this is to log in to the web client, copy everything in the "All Mail" folder (that doesn't exist elsewhere) to trash and then empty trash from the webclient. This then clears the "All Mail" folder correctly.

**Comment by LBeernaertProton** [comment] 2023-07-05 07:25
Hey @al101uk, could you confrm something for me. Is the email you are trying to delete attached one or more labels?

**Comment by al101uk** [comment] 2023-07-05 10:43
Hi,

No, the same issue happens with all mails. No mail is removed from that folder while using thunderbird.

al101uk

⁣Get BlueMail for Android ​

**Comment by LBeernaertProton** [comment] 2023-07-05 11:40
@al101uk Could you provide the bridge logs so we can see what's going on?

I was not able to reproduce what you described. When I delete messages, they get moved to Trash and once I empty trash they are removed  from All Mail. 

Do you perhaps delete messages with shift + delete?

**Comment by al101uk** [comment] 2023-07-10 12:18
Not sure if this was received...

Hi,

Logs attached.

I have tried deleting a single mail individually (right click and delete) and then emptying trash (so no shift button used), with the same result.

I also have a screen recording demonstrating the issue, but I'm unable to attach it here and I assume that's why my previous mail didn't reach github.

Regards

Alec

[logs.zip](https://github.com/ProtonMail/proton-bridge/files/12001742/logs.zip)

**Comment by al101uk** [comment] 2023-07-10 12:22
I have  log files, but they have personally identifiable information in them (email etc.) can I send them directly without the attachments showing up here. I tried sending them via normal mail along with a screen capture, but I'm not sure they were recieved?

**Comment by LBeernaertProton** [comment] 2023-07-11 08:18
@al101uk I have received your log files, thank you. I'm looking at them at the moment.

**Comment by LBeernaertProton** [comment] 2023-07-11 08:34
I have confirmed the bug. We are tracking this internally as GODT-2782.

**Comment by LBeernaertProton** [comment] 2023-07-17 07:48
@al101uk This has been fixed in the 3.3.2 release.

**Closed** 2023-09-28 14:09 UTC
Labels: bug
