### ISSUE TITLE
In-Reply-To header being removed if no References header is present

### ISSUE THREAD

**Issue by nfraprado** [ProtonMail/proton-bridge#122] opened 2020-11-01 17:39 UTC
When an email containing the `In-Reply-To` header is received by the bridge, if it also doesn't have a `References` header, the `In-Reply-To` is removed from the email header, even though RFC 2822 lists both as "SHOULD", meaning recommended, but optional nevertheless.

## Expected Behavior

The protonmail-bridge shouldn't remove the `In-Reply-To` header even if the `References` header is missing.

## Current Behavior

The absence of `References` causes `In-Reply-To` to be removed.

## Possible Solution

Just leave the header the way it is.

## Steps to Reproduce

1. Reply to an email using some client that puts the `In-Reply-To` header but not the `References` one.
2. Check that the reply doesn't get correctly indexed as an answer since `In-Reply-To` was missing.

## Context (Environment)

This was found using the aerc mail client, but it's not specific to it, and only depends on the presence of the header.
The bug ticket in aerc can be seen here: https://todo.sr.ht/~sircmpwn/aerc2/458

I'm using protonmail-bridge version 1.4.5.

**Comment by andrzejsza** [comment] 2021-06-01 07:42
could you please try with 1.8.x and confirm if that's still an issue?

**Comment by Ejdamm** [comment] 2021-06-01 15:15
I am not OP but for me reply-to does not work with 1.8.3. 

I don't know about References though. Looks like it isn't set. Reply-to is not removed but replaced with the from-address. I was sending to my gmail. 

When I send with mailtrap.io instead of protonbridge everything works just fine so I guess my code is correct.

**Comment by dopsi** [comment] 2021-08-31 07:42
Also not OP but it does still not work with 1.8.7, even if the `References` and `In-Reply-To` headers are set.

In my case, the email is sent by `git-send-email`, which sets both headers.

When replying to email from a client (Evolution for example), both headers are preserved as they were set by evolution but I cannot reproduce this behavior with git-send-email.

**Comment by andrzejsza** [comment] 2023-02-28 01:23
fixed with 3.x, closing.

**Closed by andrzejsza** 2023-02-28 01:23 UTC
