### ISSUE TITLE
Import-Export tool (ProtonBridge) is inflating the size of messages

### ISSUE THREAD

**Issue by exander77** [ProtonMail/proton-bridge#91] opened 2020-10-06 12:19 UTC
## Expected Behavior
Messages should have their size inflated.

## Current Behavior
I see an average of 15% message size inflation. 

## Possible Solution
I think it is due to base64 encoding of parts which could cause up to 25% size inflation.

## Steps to Reproduce
Compare the size of the messages before and the after import.

## Note

In my case, my messages are consuming almost 1GB more when stored on ProtonMail. On the other hand, it is also stupid on the ProtonMail end as they are consuming 15% more storage then they could be (if they are actually stored in base64 on the server).

**Comment by horejsek** [comment] 2020-10-07 06:11
Messages on ProtonMail are encrypted which results in bigger messages than the original size. That's expected behaviour.

**Comment by exander77** [comment] 2020-10-07 06:57
@horejsek What are you talking about? This is not related to encryption. This is the size of unencrypted messages. Reopen.

**Comment by cuthix** [comment] 2020-10-07 08:18
tried myself not able to reproduce

**Comment by cuthix** [comment] 2020-10-07 08:24
I am able to reproduce.. opening internal ticket

**Comment by exander77** [comment] 2020-10-07 08:58
@cuthix Thank you! This is not like we are making things up.

It does not bother me much from a user standpoint, but it has a few negatives:
1) I am not sure if it translates to ProtonMail space usage, it would be extremely unfair to users.
2) It costs additional space for locally downloaded/backed up email as well.
3) If it is really stored on ProtonMail servers like that, then cutting the space usage down by 15% would be great for ProtonMail as a company, this could save a ton of money on the infrastructure. I would advice storing all attachments it the most space-efficient way possible. If you did that, you may cut even more than that 15% as attachments are optimally encoded in general.

**Comment by bartbutler** [comment] 2020-10-09 02:52
We don't store messages encoded in base64 on the server unless the bridge is doing something like uploading encrypted MIME messages with every part encoded in base64.

**Comment by exander77** [comment] 2020-10-09 08:15
@bartbutler Yes, you spelt the problem out exactly. The bridge will encode all parts as base64 and then encrypt them, so if I am not missing something, they are being uploaded like that. But I am not that familiar with the code yet.

**Comment by cuthix** [comment] 2021-05-31 09:57
I was not able to reproduce but there might be scenarios which I didn't tried. The base64 is only used for transfer as part of OpenPGP armored message and this should not result in increased size on API side. I don't entirely understand what sizes are compared when you say 15% increase so unless we have more details (instructions how to reproduce on our side)  I will close this.

**Closed by cuthix** 2021-05-31 09:57 UTC
