### ISSUE TITLE
Account keeps logging-out

### ISSUE THREAD

**Issue by dtsdwarak** [ProtonMail/proton-bridge#15] opened 2020-04-16 16:00 UTC
Is there a way to keep the account signed-in? I had no issues while on Proton-Bridge beta. But the with the latest release (`v1.2.6`) I'm having a lot of sign outs every time, I power down my machine or log out.

Details below - 

```bash
$ uname -r
5.3.0-46-generic
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic
$ protonmail-bridge --version
Protonmail Bridge version 1.2.6 (fd4f0235fb) 2020-03-30T23:45:44+0200

```

**Comment by sirius-c** [comment] 2020-04-18 18:31
I experience a similar issue and had over a time of 10 days an email exchange with Proton, prior to this GitHub issue tracker being available. For reference, below the shortened version (starts at bottom). This is on a laptop running Xubuntu 19.10 (wireless connection). I have no problem on a desktop with Xubuntu 18.04 LTS (fixed connection).


**Me:**

One further information: after I re-enabled '"Automatically start Bridge", I check the program window right after the next boot, and it indeed showed a message similar to 'Cannot contact server'. I closed the Bridge window, and subsequently could not open it again with the system tray icon (as I reported before). On the next boot, the Bridge was disconnected.

**Me:**

To add to the observations below: after disabling '"Automatically start Bridge" and manually starting, I have not observed the disconnect problem. I could now add a delay to the autostart, but this is a little hacky and might not survive updates.

To repeat, I have not seen this problem in years of Bridge usage before.

**Me:**

After being almost positive after it worked for two days, unfortunately te issue reappeared today - but I can give a better description of what happens.

1) I disabled "Allow Alternative Routing", but left "Automatically start Bridge" enabled
2) The Bridge then worked correctly for those two days when I checked (but see below).
3) On booting this morning, I found that I cannot open the Bridge via the system tray icon. The icon looked normal, but of the menu entries 'Open', 'Help', 'Quit' did not had any effect.
4) The mail program reported 'Socket I/O times out' for the Protonmail account
5) On the next boot, I found that the Bridge was reacting again (I could open it), but it was disconnected.

I believe now that the initial step (Bridge not responding anymore) is what happens each time. There is no obvious error message in this case, unless I explicitly check the mail program, or try to open the Bridge, which I usually don't do each time.

**ProtonMail:**

Could you open the Bridge app, go to Settings, scroll down a bit and disable the "Allow Alternative Routing" option?

It is possible the Bridge app tries to connect to the Proton servers before the device is connected to the internet and this to cause the disconnect of the users.
If you wouldn't mind, could you disable the "Automatically start Bridge" option, manually start the Bridge app after you've connected successfully to the internet and see if you'll be disconnected again?

If you are, could you send us the latest logs from the Bridge so we can have additional details to debug this issue?

**Me:**

I have one bit of information to add. The connection in the bridge was again lost after this time of booting the laptop. I noticed that on using this computer just before this, the Bridge was not responding anymore - for example, I could not open the user interface via the system tray icon.

It is possible, but not 100% sure if every time, that there was similar behaviour before - the Bridge became unresponsive, and on a subsequent boot I found it disconnected from the Proton servers.

**Me:**

I use the Gnome keyring for all password storage (Chromium, Evolution, ssh keys, Protonmail Bridge), and it gets automatically unlocked when I log into my account. I used this on all of my computers, and passwords so far get retrieved always without issue.

Just an idea, could it be related to some timing issue, e.g. Protonmail trying to retrieve the password 'too soon'? It definitely does not occur on every boot, yesterday and today it did not happen. Does it depend on how quickly the Proton servers can be reached (e.g. how soon the wireless is up)?

No 'system cleaning' or alike is used, usually on Linux I have never used such tools.

**ProtonMail:**

Could you let us know if your keyring is unlocked when you log in to your User on your device?
Do you have to unlock it whenever you boot up your device independently of logging in to your User?

Do you have some kind of a Cache Cleaning software or some maintenance script on your device that runs after boot up?

**Me:**

I have not changed anything particular on this machine, other than the usual Xubuntu updates, as they come.

I cannot say with 100% certainty if this issue with logging out appeared exactly with the latest Bridge version, but I have been using the Bridge on this computer for a long time without any such log outs previously.

The log directory is attached.


**ProtonMail:**

Could you let us know if you've changed anything on your system recently?

Would you mind sending us the .log files located in Bridge->Help->Logs so we can take a look at what might be causing this issue?

**Me:**

Since the last update, I find the ProtonMail Bridge often disconnected from my ProtonMail account after rebooting (approximately after every second or third reboot), and I have to go through the connect process again, including second factor.

I was working for a long time without issues.

Xubuntu 18.10.

**Comment by sirius-c** [comment] 2020-04-20 18:24
Temporary workaround for me is to start the Bridge with a delay in the launcher `sh -c "sleep 5 && /usr/lib/protonmail/bridge/protonmail-bridge --no-window"`. But actual problem should be fixed by Proton.

**Comment by horejsek** [comment] 2020-04-27 07:51
Thanks for report. We have this in our tracker and are looking into it.

**Comment by sirius-c** [comment] 2020-05-07 15:35
Also happened now with the startup delay I mentioned above. Clear reason was that the network took a longer time to come up on the laptop, as I saw with the network status indicator.

No reason for the Bridge to disconnect for good if the network is not up at startup. However, it seems to handle later network outages correctly.

Are there news on fixing this bug? It is three weeks since the original bug report.

**Comment by jameshoulahan** [comment] 2020-05-08 07:24
I significantly reworked the way bridge gets and handles auth tokens. Unfortunately it didn't make it into the `1.2.7-beta` release yesterday but it has been merged to our development branch and is undergoing QA at the moment. I expect this to help alleviate these logout issues.

**Comment by sirius-c** [comment] 2020-05-20 11:32
Are these changes part of the 1.2.7 release that came out today?

**Comment by horejsek** [comment] 2020-05-20 11:35
Unfortunately no. Right now we are not sure which version will include the mentioned fix.

**Comment by ciehanski** [comment] 2020-06-04 20:06
I recently started experiencing consistent logouts after restarts since the 1.2.7 release on macOS.

**Comment by sirius-c** [comment] 2020-06-20 18:11
Another month has passed. Is Proton by now more sure in which version this will be fixed?

**Comment by dtsdwarak** [comment] 2020-07-03 18:19
Hi,

Is there an ETA on the fixes? 

I understand if this is being developed as a community effort but a note if this is being actively worked on from Proton's side would be much appreciated!

Thanks.

**Comment by sirius-c** [comment] 2020-08-05 06:50
A new Bridge version 1.2.8 was announced yesterday. Is this bug now fixed, @jameshoulahan? If not, what is preventing this acknowledged bug to be straightened out?

**Comment by jameshoulahan** [comment] 2020-08-05 08:59
Hi, please try bridge v1.3.2 beta, also released yesterday, which contains various fixes that should improve authentication stability.

**Comment by sirius-c** [comment] 2020-08-13 11:57
With version 1.3.3 I can now start the Bridge without suffering from the  'account log out' even without the previously needed startup delay, so possibly fixed.

**Comment by horejsek** [comment] 2020-08-13 14:25
Glad to hear that! Let us know in case the issue is back.

**Closed by horejsek** 2020-08-13 14:25 UTC
Labels: bug

**Comment by dtsdwarak** [comment] 2020-08-14 05:37
Thanks for fixing the issue.
