### ISSUE TITLE
ProtonMail Bridge crashes on Thunderbird start in Ubuntu 20.04

### ISSUE THREAD

**Issue by s75uiFbxnykgkQMC7NQh** [ProtonMail/proton-bridge#55] opened 2020-06-19 08:03 UTC
**Current Behavior**
Bridge crashes immediatelly after launching Thunderbird. The issue is occuring starting today, yesterday everithing was fine.

**Steps to Reproduce**
1. Launch ProtonMail Bridge.
2. Start Thunderbird.

**Comment by jameshoulahan** [comment] 2020-06-19 10:11
This is a duplicate of #54. My comment from there for completeness:

```
The root cause of the issue was an API change that caused some message headers to be unparseable by the go standard library's mail.ReadMessage function. This change has been rolled back; investigation is underway as to why the headers became unparseable.

Bridge was not without fault -- we did not handle failure to parse headers properly, leaving the header map nil. This has since been fixed.
```

**Closed by jameshoulahan** 2020-06-19 10:11 UTC
