### ISSUE TITLE
Doesn't work with iOS Mail

### ISSUE THREAD

**Issue by m4rkw** [ProtonMail/proton-bridge#239] opened 2021-12-09 17:17 UTC
If iOS mail is configured to use the proxy it fails to download messages. When the account is configured it passes all of the authentication tests but then hangs downloading emails.

## Expected Behavior
Emails should be downloaded

## Current Behavior
Hangs for a while and then fails with a generic error message

## Steps to Reproduce
1. Configure iOS mail to use an account on the protonmail bridge
2. Open Mail app

## Version Information
v1.8.10 for Linux

**Comment by m4rkw** [comment] 2021-12-09 19:00
Most likely because of this:

````b'34 UID SEARCH 1:* NOT DELETED\r\n'
b'34 NO unsupported search query\r\n'````

**Comment by andrzejsza** [comment] 2022-05-03 08:57
we don't support iOS ;-) also puzzled with `v1.8.10 for Linux`. if still and issue, let us know at bridge@protonmail.ch

**Comment by m4rkw** [comment] 2022-05-03 18:36
@andrzejsza Hello, thanks for getting back to me. I am somewhat confused by the response though.

1) The issue isn't specifically iOS, it's lack of support for a "NOT DELETED" search query in the IMAP implementation. Do you mean to say that you won't support this?

2) If you won't support this is there any sense in me emailing you about it?

**Comment by m4rkw** [comment] 2022-05-03 18:42
Just to explain a bit more what I'm doing here, I deployed the bridge on a hardened linux server and used stunnel4 to layer tls on top of it and then exposed the tls-wrapped endpoints. I then configured Mail on iOS to use it so I could (if it worked) use the native iOS mail client with the bridge.

Since the only thing preventing this from working is a missing feature in the IMAP implementation would you consider fixing this? There are probably other email clients that expect this to work that are also broken as a result, iOS Mail is just the only one I know of.

**Comment by andrzejsza** [comment] 2022-05-04 08:33
o wow, that's super cool, thanks for explaining.
we will support `NOT DELETED` in the future (in V3) but won't be adding it until then. will keep the issue open and report back once done.

**Comment by m4rkw** [comment] 2022-05-04 08:37
awesome thankyou. the other thing that was preventing it from working is the hard requirement for STARTTLS over smtp but I think that might have been fixed now? haven't looked recently i've been too busy. I think there was an option to disable STARTTLS but it didn't work. iOS Mail can't do STARTTLS so it just doesn't work, but if I'm layering TLS on top myself with stunnel4 then it's not necessary so just being able to disable it is all I need.

**Comment by m4rkw** [comment] 2022-05-04 08:38
Looking forward to v3 anyway :) Hopefully "nerds who know what they're doing" can become a valid use-case for the bridge :)

**Comment by andrzejsza** [comment] 2022-05-04 09:43
we don't have that requirement - you can use STARTTLS or SSL. Apple Mail is fine with any, just not plain. not sure about iOS.

**Comment by m4rkw** [comment] 2022-05-04 09:48
oh yeah that sounds right, I think I struggled to get it to work because the SSL that the proton bridge does is self-signed and iOS Mail wouldn't work even if I explicitly trusted its certificate. Is it possible to configure the birdge to use an externally-signed certificate?

**Comment by andrzejsza** [comment] 2022-05-04 11:25
yes, in principal it should be possible.

**Comment by ljanyst** [comment] 2022-05-31 20:52
I use this with the builtin iOS mail client and an externally signed certificate: https://github.com/ljanyst/peroxide

**Comment by m4rkw** [comment] 2022-05-31 20:54
> I use this with the builtin iOS mail client and an externally signed certificate: https://github.com/ljanyst/peroxide

And SMTP works? Nice

**Comment by ljanyst** [comment] 2022-05-31 21:32
Works for me.

**Comment by m4rkw** [comment] 2022-06-02 11:08
Working for me too, nice one. Apparmor profile for it was nice and simple too:

````/usr/sbin/peroxide {
  #include <abstractions/apache2-common>
  #include <abstractions/base>
  #include <abstractions/nameservice>

  network inet dgram,
  network inet stream,
  network inet6 dgram,
  network inet6 stream,

  /etc/letsencrypt/archive/rkw.io/* r,
  /etc/peroxide.conf r,
  /etc/peroxide/** rw,
  /proc/sys/net/core/* r,
  /sys/kernel/mm/transparent_hugepage/* r,
  /var/cache/peroxide/** rw,
  /var/log/peroxide/** w,
  owner /var/cache/peroxide/** rwk,
}````

**Comment by m4rkw** [comment] 2022-06-02 11:11
iOS sync is weird though. I have a very large Archive folder and for some reason it's only showing from beginning of time until early January this year. Hasn't downloaded all the messages yet and seems only occasionally indicate what it's doing. Hopefully it'll catch up eventually. It's working fine on my mac, can see everything there, probably just iOS Mail being weird.

**Comment by ljanyst** [comment] 2022-06-02 11:56
It works fine for me, but then I kind of hacked it together a couple of days ago, so there may be bugs.

Also, the bridge has UID stability issues that may play a role here: https://github.com/ProtonMail/proton-bridge/issues/220

**Comment by andrzejsza** [comment] 2023-04-14 11:03
how are you guys doing with v3? `NOT DELETED` is now supported.

**Comment by iofusion** [comment] 2023-05-21 16:49
Does Proton see value in supporting users who prefer/need to use the default iOS/iPadOS mail client?  I am happy to find this issue with a workaround and a I will try peroxide, but I am shifting to a managed email service in an effort avoid managing email services :)

**Comment by LBeernaertProton** [comment] 2023-05-22 07:07
From Bridge point of view, iOS mail client is just a mail client, so in that sense it should work. But we will not "supporting" it in the foreseeable future because Bridge was designed to run on the same machine as you have your email client, and it is not easily possible on mobile. We do not currently test this setup, and do not have any plans to do it in the future.

**Comment by gabor-meszaros** [comment] 2023-09-28 10:48
The original issue seems to be solved. I am closing this ticket.

**Closed by gabor-meszaros** 2023-09-28 10:48 UTC
Labels: enhancement, question

**Comment by gastonmorixe** [comment] 2024-02-10 01:24
1. Replace all `127.0.0.1` with `0.0.0.0` and build
2. Use Mac bridge to generate the configuration profile (`protonmail.mobileconfig`)
3. Edit the 127.0.0.1 ip with your remote bridge server, as well as the password
4. AirDrop the profile to your iPhone
5. Trust it
6. Enjoy proton in Mail app

I installed my bridge on a [Raspberry Pi 5](https://www.raspberrypi.com/products/raspberry-pi-5/)
